### ISSUE TITLE
CSD

### ISSUE THREAD

**Issue by carlosalaniz** [Angle/sat-cfdi#2]
Para los CSDs de PACs estos se obtienen a traves de la lista oficial publicada [aqui](http://omawww.sat.gob.mx/tramitesyservicios/Paginas/proveedores_autorizados_certificacion.htm) y posteriormente descargando los certificados de uno en uno con la [herramienta de recuperación](https://portalsat.plataforma.sat.gob.mx/RecuperacionDeCertificados/faces/recuperaRFC.xhtml)? O existe algun feed donde se puedan obtener todos?

**Comment by edmundofuentes** [comment]
Todos los CSDs se obtienen dinámicamente del website del SAT, y la librería mantiene un "cache" local de los certificados que va utilizando, para no consultar dos veces el mismo recurso.

Si conoces el número de certificado, lo puedes obtener con un GET en la URL del SAT, ejemplo para el certificado: 00001000000506194045 del SAT (SAT970701NN3)

https://rdc.sat.gob.mx/rccf/000010/000005/06/19/40/00001000000506194045.cer

El path de la URL es una descomposición del número de certificado: 000010 000005 06 19 40 45

Si conoces el RFC de un contribuyente, puedes utilizar la herramienta de consulta para ver el listado completo de sus certificados: https://portalsat.plataforma.sat.gob.mx/RecuperacionDeCertificados/faces/consultaCertificados.xhtml


Respondiendo a tu pregunta específica, nosotros **sí** hacemos un "bundle in" en nuestro repositorio de los CSDs del SAT, ya que estos son de uso común y así ahorramos una consulta al server del SAT.  Estos CSDs son los de los PACs que mencionas sobre la lista oficial publicada.

Este proceso no lo tenemos automatizado, y lo actualizamos manualmente de vez en cuando.

Acabo de liberar una nueva versión que arregla algunos temas sobre Root CAs faltantes. No sé si tenías algún error con eso, pero te recomiendo actualizar la librería.
